import { useState } from 'react';
import { ActivityIndicator, Image, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { authorizeWithProvider } from '@/auth/provider';
import { saveSession } from '@/auth/session';

const GREEN='#00754A';
const LOGO='https://upload.wikimedia.org/wikipedia/en/thumb/d/d3/Starbucks_Corporation_Logo_2011.svg/512px-Starbucks_Corporation_Logo_2011.svg.png';

export default function SignInScreen(){
 const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);const[loginHint,setLoginHint]=useState('');
 async function signIn(){setBusy(true);setError(null);try{const accessToken=await authorizeWithProvider(loginHint);await saveSession({accessToken});router.replace('/create-business')}catch(reason){const code=reason instanceof Error?reason.message:'sign_in_failed';setError(code==='sign_in_cancelled'?'Sign-in was cancelled.':code==='identity_provider_unavailable'?'Sign-in is temporarily unavailable.':'We could not sign you in securely.')}finally{setBusy(false)}}
 return <View style={s.container}><View style={s.mintGlow}/><Image source={{uri:LOGO}} style={s.logo}/><Text style={s.title}>Welcome back 👋</Text><Text style={s.subtitle}>Sign in to continue to Starbucks AI</Text>
 <Text style={s.label}>Email or phone</Text><View style={s.inputShell}><Text style={s.icon}>✉</Text><TextInput accessibilityLabel="Email or phone" autoCapitalize="none" autoCorrect={false} value={loginHint} onChangeText={setLoginHint} placeholder="you@company.com" placeholderTextColor="#8B949D" style={s.input}/></View>
 <Text style={s.label}>Password</Text><View style={s.inputShell}><Text style={s.icon}>▣</Text><Text style={s.password}>••••••••</Text><Text style={s.eye}>◉</Text></View><Text style={s.forgot}>Forgot password?</Text>
 {error?<View style={s.errorBox}><Text style={s.error}>{error}</Text></View>:null}
 <Pressable disabled={busy} onPress={signIn} style={({pressed})=>[s.primary,pressed&&s.pressed,busy&&s.disabled]}>{busy?<ActivityIndicator color="#FFF"/>:<Text style={s.primaryText}>Sign in</Text>}</Pressable>
 <View style={s.orRow}><View style={s.rule}/><Text style={s.orText}>or</Text><View style={s.rule}/></View>
 <View style={s.socialStack}><Social icon="G" label="Continue with Google" color="#4285F4"/><Social icon="●" label="Continue with Apple" color="#000"/><Social icon="▦" label="Continue with Microsoft" color="#00A4EF"/></View>
 <Text style={s.footer}>Don’t have an account? <Text style={s.footerStrong}>Create one</Text></Text></View>
}
function Social({icon,label,color}:{icon:string;label:string;color:string}){return <View style={s.social}><Text style={[s.socialIcon,{color}]}>{icon}</Text><Text style={s.socialText}>{label}</Text></View>}
const s=StyleSheet.create({container:{flex:1,paddingHorizontal:28,paddingTop:78,paddingBottom:36,backgroundColor:'#FFF',overflow:'hidden'},mintGlow:{position:'absolute',width:300,height:190,borderRadius:160,right:-90,top:-60,backgroundColor:'#EAF7F0'},logo:{width:78,height:78,resizeMode:'contain',marginBottom:28},title:{fontFamily:'Georgia',fontSize:34,fontWeight:'800',color:'#0B2E25'},subtitle:{fontSize:15,color:'#34423D',marginTop:8,marginBottom:34},label:{fontSize:13,fontWeight:'800',color:'#1D2925',marginBottom:8},inputShell:{minHeight:56,borderWidth:1,borderColor:'#E0E5E2',borderRadius:11,backgroundColor:'#FFF',flexDirection:'row',alignItems:'center',paddingHorizontal:14,marginBottom:22},icon:{width:28,fontSize:16,color:'#68736F'},input:{flex:1,fontSize:14,color:'#22312C'},password:{flex:1,fontSize:17,letterSpacing:5,color:'#7D8782'},eye:{fontSize:15,color:'#7F8A85'},forgot:{alignSelf:'flex-end',marginTop:-10,marginBottom:24,color:GREEN,fontSize:12,fontWeight:'700'},errorBox:{padding:10,borderRadius:9,backgroundColor:'#FDECEC',marginBottom:12},error:{color:'#A1251B',fontSize:12},primary:{minHeight:56,borderRadius:10,backgroundColor:'#008C58',alignItems:'center',justifyContent:'center'},primaryText:{color:'#FFF',fontSize:16,fontWeight:'800'},pressed:{opacity:.92},disabled:{opacity:.55},orRow:{flexDirection:'row',alignItems:'center',gap:14,marginVertical:22},rule:{flex:1,height:1,backgroundColor:'#E3E7E5'},orText:{color:'#67726C',fontSize:12},socialStack:{gap:10},social:{minHeight:52,borderRadius:10,borderWidth:1,borderColor:'#E3E7E5',backgroundColor:'#FFF',flexDirection:'row',alignItems:'center',paddingHorizontal:16},socialIcon:{width:34,fontSize:18,fontWeight:'900'},socialText:{fontSize:13,fontWeight:'700',color:'#202B27'},footer:{marginTop:'auto',textAlign:'center',fontSize:12,color:'#5E6964'},footerStrong:{color:GREEN,fontWeight:'800'}});